

# This file was *autogenerated* from the file kstar_eficiente.sage
from sage.all_cmdline import *   # import sage library

_sage_const_5 = Integer(5); _sage_const_6 = Integer(6); _sage_const_7 = Integer(7); _sage_const_13 = Integer(13); _sage_const_14 = Integer(14); _sage_const_15 = Integer(15); _sage_const_20 = Integer(20); _sage_const_21 = Integer(21); _sage_const_22 = Integer(22); _sage_const_23 = Integer(23); _sage_const_29 = Integer(29); _sage_const_31 = Integer(31); _sage_const_37 = Integer(37); _sage_const_38 = Integer(38); _sage_const_47 = Integer(47); _sage_const_53 = Integer(53); _sage_const_61 = Integer(61); _sage_const_300 = Integer(300); _sage_const_3600 = Integer(3600); _sage_const_1024p0 = RealNumber('1024.0'); _sage_const_60 = Integer(60); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_3 = Integer(3)# kstar_eficiente.sage
# Versión eficiente en RAM con registro parcial y monitoreo
# Uso: sage kstar_eficiente.sage
#
# Mejoras respecto a versión anterior:
# 1. Guarda resultados parciales en kstar_resultados.txt tras cada N
# 2. No almacena los racionales enormes en RAM (solo metadatos)
# 3. Monitoreo de RAM y tiempo por etapa
# 4. Límite de tiempo por N configurable
# 5. Reanudable: omite N ya procesados si el archivo de log existe

from sage.all import *
import time, os, sys, resource

# ── CONFIGURACIÓN ────────────────────────────────────────────
TARGETS    = [_sage_const_5 , _sage_const_6 , _sage_const_7 , _sage_const_13 , _sage_const_14 , _sage_const_15 , _sage_const_20 , _sage_const_21 , _sage_const_22 , _sage_const_23 , _sage_const_29 , _sage_const_31 , _sage_const_37 , _sage_const_38 , _sage_const_47 , _sage_const_53 , _sage_const_61 ]
MAX_K      = _sage_const_300         # máximo de iteraciones del grupo
LOG_FILE   = "kstar_resultados.txt"
MAX_TIME_N = _sage_const_3600        # segundos máximos por N (1 hora)
# ─────────────────────────────────────────────────────────────

def ram_mb():
    """RAM usada por el proceso en MB."""
    return float(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss) / _sage_const_1024p0 

def log(msg, also_print=True):
    with open(LOG_FILE, "a") as f:
        f.write(msg + "\n")
    if also_print:
        print(msg)

def ya_procesado(N):
    """Verifica si N ya tiene resultado en el log."""
    if not os.path.exists(LOG_FILE):
        return False
    with open(LOG_FILE) as f:
        return any(f"N={N}" in line and ("kstar=" in line or "NO_HALLADO" in line)
                   for line in f)

def compute_kstar_eficiente(N):
    N = Integer(N)
    t_total = time.time()

    log(f"\n{'='*_sage_const_60 }")
    log(f"N = {N}  |  RAM actual: {ram_mb():.0f} MB")

    # ── Paso 1: Curva ──────────────────────────────────────────
    E = EllipticCurve(QQ, [_sage_const_0 , _sage_const_0 , _sage_const_0 , -(N**_sage_const_2 ), _sage_const_0 ])

    # ── Paso 2: Rango (solo_use_mwrank evita 2-descent pesado) ─
    t0 = time.time()
    try:
        rk = E.rank(only_use_mwrank=True)
    except Exception:
        rk = E.rank()
    log(f"  Rango: {rk}  [{time.time()-t0:.1f}s]  RAM: {ram_mb():.0f} MB")

    if rk == _sage_const_0 :
        log(f"  RESULTADO: N={N} rango 0, no congruente.")
        return

    # ── Paso 3: Generador ──────────────────────────────────────
    t0 = time.time()
    try:
        gens = E.gens()
    except Exception as e:
        log(f"  ERROR obteniendo generador: {e}")
        return
    P = gens[_sage_const_0 ]
    h_can = float(E.height_pairing_matrix([P])[_sage_const_0 ][_sage_const_0 ])
    xP_float = float(P[_sage_const_0 ])
    xP_sign  = "negativo" if P[_sage_const_0 ] < _sage_const_0  else "positivo"
    log(f"  Generador: x(P)≈{xP_float:.6f} ({xP_sign})  h(P)={h_can:.4f}")
    log(f"  [{time.time()-t0:.1f}s]  RAM: {ram_mb():.0f} MB")

    # ── Paso 4: Iteración del grupo ────────────────────────────
    log(f"  Buscando k* con x(kP) in ({N}, {_sage_const_2 *N})...")
    t0 = time.time()
    Q = P
    hallado = False

    for k in range(_sage_const_1 , MAX_K + _sage_const_1 ):
        # Control de tiempo
        if time.time() - t_total > MAX_TIME_N:
            log(f"  TIMEOUT: N={N} excedió {MAX_TIME_N}s en k={k}")
            break

        # Usamos float para el filtro rápido, evitando aritmética exacta innecesaria
        xQ_float = float(Q[_sage_const_0 ])

        # Monitoreo cada 20 pasos
        if k % _sage_const_20  == _sage_const_0 :
            log(f"    k={k:>4}  x(kP)≈{xQ_float:.4f}  "
                f"RAM:{ram_mb():.0f}MB  t:{time.time()-t0:.0f}s",
                also_print=True)

        if float(N) < xQ_float < float(_sage_const_2 *N):
            # Hallado: ahora sí hacemos aritmética exacta
            xQ_exact = Q[_sage_const_0 ]
            ratio_exact = QQ(_sage_const_2 ) - xQ_exact / N
            n_val = ratio_exact.denominator()
            m_val = ratio_exact.numerator()

            # Verificación square-free (con número exacto)
            C = n_val * (n_val - m_val) * (_sage_const_2 *n_val - m_val) * (_sage_const_3 *n_val - m_val)
            sf_C = Integer(C).squarefree_part()
            sf_ok = (sf_C == N)

            digits_n = len(str(abs(n_val)))
            digits_m = len(str(abs(m_val)))
            ratio_float = float(ratio_exact)

            log(f"\n  ✓ HALLADO  k*={k}  x(k*P)≈{xQ_float:.6f}")
            log(f"  m/n ≈ {ratio_float:.10f}")
            log(f"  digitos(n) = {digits_n}")
            log(f"  digitos(m) = {digits_m}")
            log(f"  sf verificado: {sf_ok}")
            log(f"  Tiempo total N={N}: {time.time()-t_total:.1f}s")
            log(f"  RAM final: {ram_mb():.0f} MB")

            # Línea compacta para tabla final
            log(f"  RESULTADO: N={N} kstar={k} xkP={xQ_float:.6f} "
                f"ratio={ratio_float:.8f} hP={h_can:.4f} "
                f"digits_n={digits_n} sf_ok={sf_ok}")

            # Liberar memoria de los números grandes antes de continuar
            del n_val, m_val, C, ratio_exact
            hallado = True
            break

        # Avanzar en el grupo
        Q = Q + P

    if not hallado:
        log(f"  NO_HALLADO: N={N} en k<={MAX_K}  "
            f"Tiempo: {time.time()-t_total:.1f}s")

    # Liberar Q explícitamente
    del Q, P, E


# ── EJECUCIÓN PRINCIPAL ───────────────────────────────────────
if __name__ == "__main__":
    log(f"{'='*_sage_const_60 }")
    log(f"INICIO: {time.strftime('%Y-%m-%d %H:%M:%S')}")
    log(f"Targets: {TARGETS}")
    log(f"MAX_K={MAX_K}  MAX_TIME_N={MAX_TIME_N}s")
    log(f"{'='*_sage_const_60 }")

    for N in TARGETS:
        if ya_procesado(N):
            print(f"N={N}: ya procesado, omitiendo.")
            continue
        compute_kstar_eficiente(N)

    log(f"\n{'='*_sage_const_60 }")
    log(f"FIN: {time.strftime('%Y-%m-%d %H:%M:%S')}")

    # ── Tabla resumen desde el log ────────────────────────────
    print(f"\n{'='*_sage_const_60 }")
    print("TABLA RESUMEN (desde log)")
    print(f"{'N':>5} {'k*':>6} {'x(k*P)':>12} {'m/n':>12} "
          f"{'h(P)':>8} {'dig_n':>7} {'sf':>5}")
    print("-"*_sage_const_60 )
    if os.path.exists(LOG_FILE):
        with open(LOG_FILE) as f:
            for line in f:
                if "RESULTADO:" in line and "kstar=" in line:
                    # Parsear línea compacta
                    parts = dict(p.split("=") for p in line.split()
                                 if "=" in p and "RESULTADO" not in p)
                    try:
                        print(f"{parts['N']:>5} {parts['kstar']:>6} "
                              f"{float(parts['xkP']):>12.4f} "
                              f"{float(parts['ratio']):>12.8f} "
                              f"{float(parts['hP']):>8.4f} "
                              f"{parts['digits_n']:>7} "
                              f"{parts['sf_ok']:>5}")
                    except Exception:
                        pass
    print("="*_sage_const_60 )
    print(f"Log completo en: {LOG_FILE}")

