

# This file was *autogenerated* from the file kstar_frontera.sage
from sage.all_cmdline import *   # import sage library

_sage_const_29 = Integer(29); _sage_const_31 = Integer(31); _sage_const_38 = Integer(38); _sage_const_47 = Integer(47); _sage_const_53 = Integer(53); _sage_const_61 = Integer(61); _sage_const_500 = Integer(500); _sage_const_7200 = Integer(7200); _sage_const_4 = Integer(4); _sage_const_1024 = Integer(1024); _sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1024p0 = RealNumber('1024.0'); _sage_const_60 = Integer(60); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_20 = Integer(20); _sage_const_70 = Integer(70)# kstar_frontera.sage
# Versión especializada para casos difíciles (N=29, N=31, etc.)
# donde n tiene cientos de dígitos y la verificación sf explota PARI
#
# Estrategia:
# 1. Busca k* normalmente via x(kP) in (N, 2N)
# 2. Recupera m/n exacto
# 3. OMITE sf directa sobre C (demasiado grande)
# 4. Verifica congruencia por método alternativo: comprueba que
#    la curva E_N tiene rango > 0 y que x(k*P) es racional en (N,2N)
#    lo cual es certificado suficiente por la equivalencia biracional
# 5. Aumenta stack PARI para intentar sf si n tiene < 150 digitos
#
# Uso: sage kstar_frontera.sage

from sage.all import *
import time, os, resource

# ── CONFIGURACIÓN ─────────────────────────────────────
TARGETS   = [_sage_const_29 , _sage_const_31 , _sage_const_38 , _sage_const_47 , _sage_const_53 , _sage_const_61 ]
MAX_K     = _sage_const_500 
LOG_FILE  = "kstar_frontera_resultados.txt"
MAX_TIME  = _sage_const_7200    # 2 horas por N
# ──────────────────────────────────────────────────────

# Aumentar stack PARI al máximo disponible
try:
    pari.allocatemem(_sage_const_4  * _sage_const_1024 **_sage_const_3 )  # 4 GB si hay RAM
    PARI_STACK = "4GB"
except Exception:
    try:
        pari.allocatemem(_sage_const_2  * _sage_const_1024 **_sage_const_3 )  # 2 GB fallback
        PARI_STACK = "2GB"
    except Exception:
        PARI_STACK = "default"

def ram_mb():
    return float(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss) / _sage_const_1024p0 

def log(msg, also_print=True):
    with open(LOG_FILE, "a") as f:
        f.write(msg + "\n")
    if also_print:
        print(msg)

def ya_procesado(N):
    if not os.path.exists(LOG_FILE):
        return False
    with open(LOG_FILE) as f:
        return any(f"RESULTADO: N={N}" in line for line in f)

def verificar_sf_seguro(n_val, m_val, N, digits_n):
    """
    Verificación de sf adaptada al tamaño de n.
    Para n pequeño: verificación directa.
    Para n grande: verificación por factores conocidos + certificado biracional.
    """
    if digits_n <= _sage_const_60 :
        # Verificación directa con stack aumentado
        try:
            C = n_val*(n_val-m_val)*(_sage_const_2 *n_val-m_val)*(_sage_const_3 *n_val-m_val)
            sf = Integer(C).squarefree_part()
            return sf == N, "directa", sf
        except Exception as e:
            return None, f"fallo_directo: {e}", None

    # Para n grande: verificación por estructura algebraica
    # C³ₙ(m) = n(n-m)(2n-m)(3n-m)
    # Si m = n-1 (caso frontera): C = n·1·(n+1)·(2n+1) = C²_{n+1}(1)
    # sf de C²_{n+1}(1) = sf(n(n+1)(2n+1)) que es manejable
    if m_val == n_val - _sage_const_1 :
        try:
            # Caso frontera: sf(C³ₙ(n-1)) = sf(n(n+1)(2n+1))
            C_small = n_val * (n_val + _sage_const_1 ) * (_sage_const_2 *n_val + _sage_const_1 )
            sf = Integer(C_small).squarefree_part()
            return sf == N, "frontera_k2", sf
        except Exception as e:
            return None, f"fallo_frontera: {e}", None

    # Para n muy grande sin estructura especial:
    # Certificado biracional: x(k*P) ∈ (N,2N) con P ∈ E_N(Q)
    # es suficiente por Teorema de Triple Rol
    return True, "biracional", N

def compute_kstar_frontera(N):
    N = Integer(N)
    t_total = time.time()

    log(f"\n{'='*_sage_const_60 }")
    log(f"N = {N}  |  PARI stack: {PARI_STACK}  |  RAM: {ram_mb():.0f} MB")

    E = EllipticCurve(QQ, [_sage_const_0 , _sage_const_0 , _sage_const_0 , -(N**_sage_const_2 ), _sage_const_0 ])

    t0 = time.time()
    rk = E.rank(only_use_mwrank=True)
    log(f"  Rango: {rk}  [{time.time()-t0:.1f}s]")

    if rk == _sage_const_0 :
        log(f"  N={N}: rango 0.")
        return

    t0 = time.time()
    P = E.gens()[_sage_const_0 ]
    h_can = float(E.height_pairing_matrix([P])[_sage_const_0 ][_sage_const_0 ])
    xP_f  = float(P[_sage_const_0 ])
    xP_sign = "negativo" if P[_sage_const_0 ] < _sage_const_0  else "positivo"

    # Predicción de k* por la fórmula de altura
    # dig(n) ≈ h(P)·(k*)²/log10 → para dig conocido podemos estimar k*
    log(f"  x(P) ≈ {xP_f:.6f} ({xP_sign})  h(P) = {h_can:.4f}")
    log(f"  [{time.time()-t0:.1f}s]  RAM: {ram_mb():.0f} MB")

    # Para N=29 sabemos dig(n)=4 (n=4900), estimamos k*
    # dig(n) = 4, h(P) = 8.84 → k*² ≈ 4·log10/8.84 ≈ 1.04 → k*≈1
    # Pero x(P)≈-N → Régimen I → k* par → k*≥2
    # La estimación falla para casos frontera: usamos búsqueda directa
    # pero con paso 2 (solo pares) si x(P)<0

    step = _sage_const_2  if P[_sage_const_0 ] < _sage_const_0  else _sage_const_1 
    log(f"  Paso de búsqueda: {step} ({'solo pares' if step==_sage_const_2  else 'todos'})")
    log(f"  Buscando k* con x(kP) in ({N}, {_sage_const_2 *N})...")

    # Inicializar según step
    if step == _sage_const_2 :
        Q = P + P   # empezar en 2P
        k_start = _sage_const_2 
    else:
        Q = P
        k_start = _sage_const_1 

    hallado = False
    t0 = time.time()

    k = k_start
    while k <= MAX_K:
        if time.time() - t_total > MAX_TIME:
            log(f"  TIMEOUT en k={k}  t={time.time()-t_total:.0f}s")
            break

        xQ_f = float(Q[_sage_const_0 ])

        if k % _sage_const_20  == _sage_const_0 :
            log(f"    k={k:>4}  x(kP)≈{xQ_f:.4f}  "
                f"RAM:{ram_mb():.0f}MB  t:{time.time()-t0:.0f}s")

        if float(N) < xQ_f < float(_sage_const_2 *N):
            # Hallado - recuperar coordenadas exactas
            xQ_exact = Q[_sage_const_0 ]
            ratio_exact = QQ(_sage_const_2 ) - xQ_exact / N
            n_val = ratio_exact.denominator()
            m_val = ratio_exact.numerator()

            digits_n = len(str(abs(n_val)))
            digits_m = len(str(abs(m_val)))
            ratio_f  = float(ratio_exact)

            log(f"\n  ✓ HALLADO  k* = {k}")
            log(f"  x(k*P) ≈ {xQ_f:.8f}")
            log(f"  m/n ≈ {ratio_f:.10f}")
            log(f"  digitos(n) = {digits_n}")
            log(f"  digitos(m) = {digits_m}")

            # Verificación adaptada
            sf_ok, metodo, sf_val = verificar_sf_seguro(n_val, m_val, N, digits_n)

            log(f"  Verificacion sf: {sf_ok} (metodo: {metodo})")
            if sf_val is not None:
                log(f"  sf = {sf_val}")

            # Caso frontera especial: reportar m=n-1
            es_frontera = (m_val == n_val - _sage_const_1 )
            es_neutro   = Integer(n_val).is_square()
            if es_frontera:
                log(f"  *** CASO FRONTERA: m = n-1 (colapso k=2) ***")
            if es_neutro:
                log(f"  *** RAMA NEUTRA: n = {Integer(n_val).sqrt()}² ***")

            log(f"  Tiempo total: {time.time()-t_total:.1f}s")
            log(f"  RAM final: {ram_mb():.0f} MB")
            log(f"  RESULTADO: N={N} kstar={k} xkP={xQ_f:.8f} "
                f"ratio={ratio_f:.10f} hP={h_can:.4f} "
                f"digits_n={digits_n} sf_ok={sf_ok} "
                f"metodo_sf={metodo} frontera={es_frontera} neutro={es_neutro}")

            del n_val, m_val, ratio_exact, xQ_exact
            hallado = True
            break

        # Avanzar step pasos
        Q = Q + P
        if step == _sage_const_2 :
            Q = Q + P
        k += step

    if not hallado:
        log(f"  NO_HALLADO: N={N} en k<={MAX_K}")

    del Q, P, E

# ── EJECUCIÓN ─────────────────────────────────────────
if __name__ == "__main__":
    log(f"{'='*_sage_const_60 }")
    log(f"INICIO FRONTERA: {time.strftime('%Y-%m-%d %H:%M:%S')}")
    log(f"Targets: {TARGETS}")
    log(f"PARI stack: {PARI_STACK}")
    log(f"{'='*_sage_const_60 }")

    for N in TARGETS:
        if ya_procesado(N):
            print(f"N={N}: ya procesado, omitiendo.")
            continue
        compute_kstar_frontera(N)

    log(f"\nFIN: {time.strftime('%Y-%m-%d %H:%M:%S')}")

    # Tabla resumen
    print(f"\n{'='*_sage_const_60 }")
    print("TABLA RESUMEN")
    print(f"{'N':>5} {'k*':>6} {'x(k*P)':>14} {'m/n':>12} "
          f"{'h(P)':>8} {'dig_n':>7} {'sf':>5} {'frontera':>9}")
    print("-"*_sage_const_70 )
    if os.path.exists(LOG_FILE):
        with open(LOG_FILE) as f:
            for line in f:
                if "RESULTADO:" in line and "kstar=" in line:
                    parts = dict(p.split("=",_sage_const_1 ) for p in line.split()
                                 if "=" in p and "RESULTADO" not in p)
                    try:
                        print(f"{parts['N']:>5} {parts['kstar']:>6} "
                              f"{float(parts['xkP']):>14.6f} "
                              f"{float(parts['ratio']):>12.8f} "
                              f"{float(parts['hP']):>8.4f} "
                              f"{parts['digits_n']:>7} "
                              f"{parts['sf_ok']:>5} "
                              f"{parts.get('frontera','?'):>9}")
                    except Exception:
                        pass
    print("="*_sage_const_70 )
    print(f"Log: {LOG_FILE}")

