

# This file was *autogenerated* from the file validation_k3_complete.sage
from sage.all_cmdline import *   # import sage library

_sage_const_210 = Integer(210); _sage_const_100 = Integer(100); _sage_const_5 = Integer(5); _sage_const_6 = Integer(6); _sage_const_7 = Integer(7); _sage_const_13 = Integer(13); _sage_const_14 = Integer(14); _sage_const_15 = Integer(15); _sage_const_20 = Integer(20); _sage_const_21 = Integer(21); _sage_const_22 = Integer(22); _sage_const_23 = Integer(23); _sage_const_29 = Integer(29); _sage_const_31 = Integer(31); _sage_const_37 = Integer(37); _sage_const_38 = Integer(38); _sage_const_47 = Integer(47); _sage_const_53 = Integer(53); _sage_const_61 = Integer(61); _sage_const_300 = Integer(300); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_0 = Integer(0); _sage_const_65 = Integer(65); _sage_const_50 = Integer(50); _sage_const_1 = Integer(1); _sage_const_1p0 = RealNumber('1.0'); _sage_const_2p0 = RealNumber('2.0'); _sage_const_18 = Integer(18); _sage_const_100p0 = RealNumber('100.0'); _sage_const_80 = Integer(80); _sage_const_4 = Integer(4); _sage_const_40 = Integer(40); _sage_const_10 = Integer(10); _sage_const_0p8886 = RealNumber('0.8886'); _sage_const_4p2531 = RealNumber('4.2531'); _sage_const_8 = Integer(8); _sage_const_118 = Integer(118); _sage_const_8p8437 = RealNumber('8.8437'); _sage_const_72 = Integer(72); _sage_const_19911 = Integer(19911); _sage_const_13p5654 = RealNumber('13.5654'); _sage_const_16 = Integer(16); _sage_const_16p6107 = RealNumber('16.6107'); _sage_const_116 = Integer(116); _sage_const_55 = Integer(55)# validation_k3_complete.sage
# Validacion completa del framework del operador k=3
# Cubre: Tabla 3, Tablas 7-11, anchor pairs, curvas E_m,
#        rangos, orbita Mordell-Weil y regimen I/II/III
#
# Uso: sage validation_k3_complete.sage

from sage.all import *
import time, os

# -- CONFIGURACION ----------------------------------------------------
LOG_FILE      = "validation_k3_results.txt"
N_210         = _sage_const_210 
N_MAX_ANCHOR  = _sage_const_100 
M_MAX_EM      = _sage_const_100 
X_BOUND_EM    = _sage_const_100 
TARGETS_MW    = [_sage_const_5 , _sage_const_6 , _sage_const_7 , _sage_const_13 , _sage_const_14 , _sage_const_15 , _sage_const_20 , _sage_const_21 , _sage_const_22 , _sage_const_23 ,
                 _sage_const_29 , _sage_const_31 , _sage_const_37 , _sage_const_38 , _sage_const_47 , _sage_const_53 , _sage_const_61 ]
MAX_K         = _sage_const_300 
# ---------------------------------------------------------------------

# -- UTILIDADES -------------------------------------------------------

def sf(x):
    return Integer(x).squarefree_part()

def C3(n, m):
    n, m = Integer(n), Integer(m)
    return n * (n - m) * (_sage_const_2 *n - m) * (_sage_const_3 *n - m)

def is_perfect_square(x):
    if x < _sage_const_0 :
        return False, Integer(_sage_const_0 )
    s = Integer(x).isqrt()
    return (s * s == x), s

def log_msg(msg, f=None, also_print=True):
    if also_print:
        print(msg)
    if f:
        f.write(msg + "\n")
        f.flush()

# =====================================================================
# BLOQUE 1: TABLA 3 -- Ratios R = x/N para N = 210
# Correccion: R = x/N directamente desde Lema 23
# =====================================================================

def tabla_3_ratios(N, max_multiples, f):
    log_msg("\n" + "="*_sage_const_65 , f)
    log_msg("BLOQUE 1: Tabla 3 -- Ratios R = x/N para N = %d" % N, f)
    log_msg("="*_sage_const_65 , f)

    E = EllipticCurve(QQ, [_sage_const_0 , _sage_const_0 , _sage_const_0 , -Integer(N)**_sage_const_2 , _sage_const_0 ])
    rk = E.rank()
    log_msg("  E_%d: rango = %d" % (N, rk), f)
    if rk == _sage_const_0 :
        log_msg("  Rango 0: N=%d no es congruente." % N, f)
        return

    P = E.gens()[_sage_const_0 ]
    log_msg("  Generador P: x(P) = %.6f" % float(P[_sage_const_0 ]), f)
    log_msg("\n  %4s %20s %10s %10s" % ("n", "x(nP)", "R=x/N", "En (1,2)?"), f)
    log_msg("  " + "-"*_sage_const_50 , f)

    count_in_range = _sage_const_0 
    Q = P
    for k in range(_sage_const_1 , max_multiples + _sage_const_1 ):
        x = Q[_sage_const_0 ]
        R = QQ(x) / QQ(N)
        R_float = float(R)
        in_range = _sage_const_1p0  < R_float < _sage_const_2p0 
        if in_range:
            count_in_range += _sage_const_1 
        marker = "SI" if in_range else "NO"
        x_str = str(x)[:_sage_const_18 ]
        log_msg("  %4d %20s %10.4f %10s" % (k, x_str, R_float, marker), f)
        Q = Q + P

    pct = _sage_const_100p0  * count_in_range / max_multiples
    log_msg("\n  En rango (1,2): %d/%d (%.1f%%)" % (
        count_in_range, max_multiples, pct), f)

# =====================================================================
# BLOQUE 2: TABLAS 7-8 -- Anchor Pairs
# Condicion: C3(n,m) = 4j^2 - 2jm  y  Delta = (4j-m)^2
# =====================================================================

def tabla_7_anchor_pairs(n_max, f):
    log_msg("\n" + "="*_sage_const_65 , f)
    log_msg("BLOQUE 2: Anchor Pairs -- n <= %d" % n_max, f)
    log_msg("  Condicion: C3(n,m) = 4j^2 - 2jm,  Delta = (4j-m)^2", f)
    log_msg("="*_sage_const_65 , f)

    pairs = []
    log_msg("  %3s %5s %5s %7s %14s %14s %10s %7s %7s" % (
        "#", "n", "m", "j", "C=C3(n,m)", "bj=4j^2-2jm",
        "Delta", "sqrt", "u/v"), f)
    log_msg("  " + "-"*_sage_const_80 , f)

    count = _sage_const_0 
    m_distribution = {}

    for n in range(_sage_const_2 , n_max + _sage_const_1 ):
        for m in range(_sage_const_1 , n):
            C = C3(n, m)
            if C <= _sage_const_0 :
                continue

            Delta = m*m + _sage_const_4 *C
            is_sq, s = is_perfect_square(Delta)
            if not is_sq:
                continue

            if (m + s) % _sage_const_4  != _sage_const_0 :
                continue

            j = (m + s) // _sage_const_4 
            if j <= _sage_const_0 :
                continue

            bj = _sage_const_4 *j*j - _sage_const_2 *j*m
            if bj != C:
                continue

            # Verificacion de traduccion: y = 4j - m debe ser sqrt(Delta)
            y_check = _sage_const_4 *j - m
            if y_check != s:
                log_msg("  ERROR traduccion: n=%d, m=%d" % (n, m), f)
                continue

            u = _sage_const_2 *n - m
            v = n
            uv = float(QQ(u) / QQ(v))

            count += _sage_const_1 
            pairs.append((n, m, j, int(C), int(bj), int(Delta), int(s), uv))
            m_distribution[m] = m_distribution.get(m, _sage_const_0 ) + _sage_const_1 

            log_msg("  %3d %5d %5d %7d %14d %14d %10d %7d %7.3f" % (
                count, n, m, j, C, bj, Delta, s, uv), f)

    log_msg("\n  Total anchor pairs encontrados: %d" % count, f)
    log_msg("  (Preprint reporta 24 para n <= 100)", f)

    log_msg("\n  Distribucion por m:", f)
    log_msg("  %5s %6s" % ("m", "count"), f)
    for m_val in sorted(m_distribution.keys()):
        log_msg("  %5d %6d" % (m_val, m_distribution[m_val]), f)
    log_msg("  Distintos valores de m: %d" % len(m_distribution), f)
    log_msg("  (Preprint reporta 19 valores de m)", f)

    return pairs, m_distribution

# =====================================================================
# BLOQUE 3: TABLAS 9-11 -- Puntos enteros en E_m y rangos estimados
# E_m: y^2 = m^2 + 4n(n-m)(2n-m)(3n-m)
# =====================================================================

def tabla_9_11_curvas_Em(m_values, x_bound, f):
    log_msg("\n" + "="*_sage_const_65 , f)
    log_msg("BLOQUE 3: Curvas E_m -- puntos enteros y rangos", f)
    log_msg("  Curva: y^2 = m^2 + 4n(n-m)(2n-m)(3n-m)", f)
    log_msg("  Busqueda: n in [1, %d]" % x_bound, f)
    log_msg("="*_sage_const_65 , f)

    rank_count = {_sage_const_2 : _sage_const_0 , _sage_const_3 : _sage_const_0 }
    total_points = _sage_const_0 
    all_curve_data = []

    for m in sorted(m_values):
        m = Integer(m)
        points = []

        for n in range(_sage_const_1 , x_bound + _sage_const_1 ):
            n_i = Integer(n)
            if n_i <= m:
                continue
            C = C3(n_i, m)
            if C <= _sage_const_0 :
                continue
            rhs = m*m + _sage_const_4 *C
            is_sq, s = is_perfect_square(rhs)
            if is_sq:
                points.append((int(n_i), int(s)))

        total_points += len(points)

        # Estimacion de rango por numero de puntos
        # Heuristica del preprint: k<=2 -> rango 0, k in [3,4] -> rango 1-2,
        # k in [5,10] -> rango >= 2, k > 10 -> rango >= 3
        k = len(points)
        if k <= _sage_const_2 :
            est_rank = _sage_const_2 
        elif k <= _sage_const_4 :
            est_rank = _sage_const_2 
        else:
            est_rank = _sage_const_3 

        if est_rank >= _sage_const_3 :
            rank_count[_sage_const_3 ] += _sage_const_1 
        else:
            rank_count[_sage_const_2 ] += _sage_const_1 

        pts_str = ", ".join(["(%d,%d)" % (nn, yy) for nn, yy in points[:_sage_const_4 ]])
        if len(points) > _sage_const_4 :
            pts_str += "..."

        log_msg("\n  E_%d: %d puntos, rango est. >= %d" % (
            int(m), len(points), est_rank), f)
        if points:
            log_msg("    Puntos (n,y): %s" % pts_str, f)

        all_curve_data.append((int(m), len(points), est_rank, points))

    total_curves = len(m_values)
    log_msg("\n  " + "="*_sage_const_40 , f)
    log_msg("  DISTRIBUCION DE RANGOS ESTIMADOS:", f)
    log_msg("  Rango = 2:  %d curvas (%.1f%%)" % (
        rank_count[_sage_const_2 ], _sage_const_100p0 *rank_count[_sage_const_2 ]/total_curves), f)
    log_msg("  Rango >= 3: %d curvas (%.1f%%)" % (
        rank_count[_sage_const_3 ], _sage_const_100p0 *rank_count[_sage_const_3 ]/total_curves), f)
    log_msg("  Total puntos enteros: %d" % total_points, f)
    log_msg("  (Preprint: 76 puntos, 57.9%% rango 2, 42.1%% rango >=3)", f)

    return all_curve_data

# =====================================================================
# BLOQUE 4: TABLA 5 -- Orbita Mordell-Weil con regimen I/II/III
# =====================================================================

def clasificar_regimen(xP, N):
    xP_f = float(xP)
    N_f  = float(N)
    if xP_f < _sage_const_0 :
        return "I"
    elif N_f < xP_f < _sage_const_2p0 *N_f:
        return "II"
    else:
        return "III"

def tabla_5_mordell_weil(targets, max_k, f):
    log_msg("\n" + "="*_sage_const_65 , f)
    log_msg("BLOQUE 4: Tabla 5 -- Orbita Mordell-Weil completa", f)
    log_msg("  Targets: %s" % str(targets), f)
    log_msg("="*_sage_const_65 , f)

    log_msg("  %4s %4s %8s %5s %12s %10s %7s %6s %9s %6s" % (
        "N", "Reg", "h(P)", "k*", "x(k*P)", "m/n",
        "dig(n)", "sf_ok", "pred_dig", "err%"), f)
    log_msg("  " + "-"*_sage_const_80 , f)

    for N in targets:
        N = Integer(N)
        t0 = time.time()

        E = EllipticCurve(QQ, [_sage_const_0 , _sage_const_0 , _sage_const_0 , -N**_sage_const_2 , _sage_const_0 ])

        try:
            rk = E.rank(only_use_mwrank=True)
        except Exception:
            try:
                rk = E.rank()
            except Exception:
                log_msg("  %4d  rango no calculable" % int(N), f)
                continue

        if rk == _sage_const_0 :
            log_msg("  %4d  N no congruente (rango 0)" % int(N), f)
            continue

        try:
            P = E.gens()[_sage_const_0 ]
        except Exception as e:
            log_msg("  %4d  error generador: %s" % (int(N), str(e)), f)
            continue

        h_can   = float(E.height_pairing_matrix([P])[_sage_const_0 ][_sage_const_0 ])
        xP      = P[_sage_const_0 ]
        regimen = clasificar_regimen(xP, N)

        Q = P
        hallado = False
        kstar   = None
        xkP     = None

        for k in range(_sage_const_1 , max_k + _sage_const_1 ):
            xQ_f = float(Q[_sage_const_0 ])
            if float(N) < xQ_f < float(_sage_const_2 *N):
                kstar = k
                xkP   = Q[_sage_const_0 ]
                hallado = True
                break
            Q = Q + P

        if not hallado:
            log_msg("  %4d %4s %8.4f  k* no hallado en k<=%d" % (
                int(N), regimen, h_can, max_k), f)
            continue

        # Traduccion a (n, m) via Corolario 29
        ratio  = QQ(_sage_const_2 ) - QQ(xkP) / QQ(N)
        denom  = ratio.denominator()
        numer  = ratio.numerator()
        dig_n  = len(str(abs(denom)))

        C      = C3(denom, numer)
        sf_val = sf(C) if C > _sage_const_0  else Integer(-_sage_const_1 )
        sf_ok  = (sf_val == N)

        pred_dig = h_can * kstar**_sage_const_2  / float(RR(_sage_const_10 ).log())
        err_pct  = abs(pred_dig - dig_n) / max(dig_n, _sage_const_1 ) * _sage_const_100p0 

        log_msg("  %4d %4s %8.4f %5d %12.4f %10.6f %7d %6s %9.1f %6.2f%%" % (
            int(N), regimen, h_can, kstar,
            float(xkP), float(ratio),
            dig_n, str(sf_ok),
            pred_dig, err_pct), f)

        elapsed = time.time() - t0
        log_msg("    [%.1fs]" % elapsed, f, also_print=False)

# =====================================================================
# BLOQUE 5: JERARQUIA SIEGEL
# Verifica: anchor pairs subset de puntos enteros de E_m
# =====================================================================

def verificar_jerarquia_siegel(pairs, curve_data, f):
    log_msg("\n" + "="*_sage_const_65 , f)
    log_msg("BLOQUE 5: Verificacion jerarquia Siegel", f)
    log_msg("  Anchor pairs subset {puntos enteros E_m, n>0, m<n}", f)
    log_msg("="*_sage_const_65 , f)

    siegel_index = {}
    for m, n_pts, est_rank, points in curve_data:
        siegel_index[m] = set((nn, yy) for nn, yy in points)

    ok_count   = _sage_const_0 
    fail_count = _sage_const_0 

    for n, m, j, C, bj, Delta, s, uv in pairs:
        m_int = int(m)
        n_int = int(n)
        y_anchor = s  # y = 4j - m = sqrt(Delta)

        in_siegel = (m_int in siegel_index and
                     (n_int, y_anchor) in siegel_index[m_int])

        if in_siegel:
            ok_count += _sage_const_1 
        else:
            fail_count += _sage_const_1 
            log_msg("  FALLO: anchor pair (n=%d,m=%d,j=%d) "
                    "no en puntos Siegel de E_%d" % (n, m, j, m), f)

    log_msg("\n  Anchor pairs en Siegel: %d/%d" % (
        ok_count, ok_count + fail_count), f)

    if fail_count == _sage_const_0 :
        log_msg("  OK: jerarquia confirmada en rango de busqueda", f)
    else:
        log_msg("  AVISO: %d pares fuera de rango "
                "(aumentar X_BOUND_EM)" % fail_count, f)

# =====================================================================
# BLOQUE 6: TABLA 6 -- Validacion formula de digitos
# dig(n) aprox h(P) * (k*)^2 / log(10)
# =====================================================================

def tabla_6_formula_digitos(f):
    log_msg("\n" + "="*_sage_const_65 , f)
    log_msg("BLOQUE 6: Tabla 6 -- Validacion formula dig(n)", f)
    log_msg("  dig(n) aprox h(P) * (k*)^2 / log(10)", f)
    log_msg("="*_sage_const_65 , f)

    # Datos del preprint (Tabla 5 y 6)
    datos = [
        # (N,   h_P,     k*,  dig_n_obs)
        (_sage_const_6 ,    _sage_const_0p8886 ,   _sage_const_2 ,   _sage_const_2 ),
        (_sage_const_22 ,   _sage_const_4p2531 ,   _sage_const_8 ,   _sage_const_118 ),
        (_sage_const_29 ,   _sage_const_8p8437 ,   _sage_const_72 ,  _sage_const_19911 ),
        (_sage_const_37 ,   _sage_const_13p5654 ,  _sage_const_16 ,  None),
        (_sage_const_61 ,   _sage_const_16p6107 ,  _sage_const_4 ,   _sage_const_116 ),
    ]

    log_msg("  %4s %8s %5s %8s %8s %8s %8s" % (
        "N", "h(P)", "k*", "(k*)^2", "Pred", "Obs", "Error"), f)
    log_msg("  " + "-"*_sage_const_55 , f)

    for N, hP, ks, obs in datos:
        pred = hP * ks**_sage_const_2  / float(RR(_sage_const_10 ).log())
        if obs is not None:
            err     = abs(pred - obs) / obs * _sage_const_100p0 
            err_str = "%.2f%%" % err
            obs_str = str(obs)
        else:
            err_str = "N/A"
            obs_str = "~300"
        log_msg("  %4d %8.4f %5d %8d %8.1f %8s %8s" % (
            N, hP, ks, ks**_sage_const_2 , pred, obs_str, err_str), f)

# =====================================================================
# EJECUCION PRINCIPAL
# =====================================================================

with open(LOG_FILE, "w") as f:
    log_msg("VALIDACION COMPLETA DEL OPERADOR k=3", f)
    log_msg("Timestamp: %s" % time.strftime('%Y-%m-%d %H:%M:%S'), f)
    log_msg("="*_sage_const_65 , f)

    # B1: Tabla 3
    tabla_3_ratios(N_210, _sage_const_20 , f)

    # B2: Tablas 7-8 -- Anchor pairs
    pairs, m_dist = tabla_7_anchor_pairs(N_MAX_ANCHOR, f)

    # B3: Tablas 9-11 -- Curvas E_m
    m_vals = sorted(m_dist.keys())
    curve_data = tabla_9_11_curvas_Em(m_vals, X_BOUND_EM, f)

    # B4: Tabla 5 -- Orbita Mordell-Weil con regimen
    tabla_5_mordell_weil(TARGETS_MW, MAX_K, f)

    # B5: Jerarquia Siegel
    verificar_jerarquia_siegel(pairs, curve_data, f)

    # B6: Tabla 6 -- Formula digitos
    tabla_6_formula_digitos(f)

    log_msg("\n" + "="*_sage_const_65 , f)
    log_msg("FIN: %s" % time.strftime('%Y-%m-%d %H:%M:%S'), f)
    log_msg("Log completo en: %s" % LOG_FILE, f)

