

# This file was *autogenerated* from the file verificar_N21.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1en10 = RealNumber('1e-10'); _sage_const_1en12 = RealNumber('1e-12'); _sage_const_3p0 = RealNumber('3.0'); _sage_const_2p0 = RealNumber('2.0'); _sage_const_21 = Integer(21); _sage_const_2 = Integer(2); _sage_const_1p6615 = RealNumber('1.6615'); _sage_const_64 = Integer(64); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_800 = Integer(800); _sage_const_2000 = Integer(2000); _sage_const_5000 = Integer(5000); _sage_const_10000 = Integer(10000); _sage_const_20000 = Integer(20000); _sage_const_6 = Integer(6); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_14 = Integer(14); _sage_const_8 = Integer(8); _sage_const_10 = Integer(10); _sage_const_12 = Integer(12); _sage_const_20 = Integer(20); _sage_const_100 = Integer(100); _sage_const_1p0 = RealNumber('1.0'); _sage_const_11 = Integer(11); _sage_const_0p19 = RealNumber('0.19'); _sage_const_0p05 = RealNumber('0.05'); _sage_const_0p02 = RealNumber('0.02')# ============================================================
# Verificación de N=21: ¿outlier estructural o convergencia
# al Régimen I con muestra suficiente?
# ============================================================
# Estrategia: correr el análisis para N=21 con muestras
# crecientes (800, 2000, 5000, 10000, 20000 puntos) y observar
# si freq y M4 convergen hacia los valores típicos del Régimen I
# (freq ≈ 0.22, M4 ≈ 2.60) o se estabilizan en valores distintos.
# ============================================================
# Uso: sage verificar_N21.sage | tee resultado_N21.txt
# ============================================================

import numpy as np

# ── Ley de adición de Weierstrass en float64 puro ────────────
def ec_add(x1, y1, x2, y2, a):
    """Adición en y² = x³ + ax. Punto al infinito = (inf, inf)."""
    if np.isinf(x1): return (x2, y2)
    if np.isinf(x2): return (x1, y1)
    if abs(x1 - x2) < _sage_const_1en10  and abs(y1 + y2) < _sage_const_1en10 :
        return (np.inf, np.inf)
    if abs(x1 - x2) < _sage_const_1en10  and abs(y1 - y2) < _sage_const_1en10 :
        if abs(y1) < _sage_const_1en12 :
            return (np.inf, np.inf)
        lam = (_sage_const_3p0 *x1*x1 + a) / (_sage_const_2p0 *y1)
    else:
        lam = (y2 - y1) / (x2 - x1)
    x3 = lam*lam - x1 - x2
    y3 = lam*(x1 - x3) - y1
    return (x3, y3)

# ── Parámetros de N=21 ───────────────────────────────────────
N      = _sage_const_21 
a      = -float(N)**_sage_const_2        # curva: y² = x³ − 441x
REG    = 'I'
KSTAR  = _sage_const_2 
H_CANON = _sage_const_1p6615 

# Obtener generador exacto (una sola vez)
print("="*_sage_const_64 )
print(f"  N=21  Régimen {REG}  k*={KSTAR}  ĥ(P)={H_CANON}")
print("="*_sage_const_64 )
print("  Calculando generador sobre QQ...", end="", flush=True)

E = EllipticCurve([-N**_sage_const_2 , _sage_const_0 ])
G = E.gens()
P_QQ = G[_sage_const_0 ]
px = float(P_QQ[_sage_const_0 ])
py = float(P_QQ[_sage_const_1 ])
print(f" hecho.")
print(f"  x(P) = {px:.6f}   y(P) = {py:.6f}")
print(f"  x(P) < 0 → generador en oval acotada C₀ (Régimen I confirmado)")
print()

# Muestras crecientes
MUESTRAS = [_sage_const_800 , _sage_const_2000 , _sage_const_5000 , _sage_const_10000 , _sage_const_20000 ]

# Pre-calcular la órbita completa hasta max(MUESTRAS) de una sola vez
MAX_K = max(MUESTRAS)
print(f"  Calculando órbita completa hasta k={MAX_K}...", flush=True)

xs_orbit = np.empty(MAX_K)   # x(kP) para k=1..MAX_K
qx, qy = px, py
for i in range(MAX_K):
    if np.isinf(qx):
        xs_orbit[i] = np.nan
    else:
        xs_orbit[i] = qx
    qx, qy = ec_add(qx, qy, px, py, a)

print(f"  Órbita calculada.\n")

# ── Análisis por tamaño de muestra ──────────────────────────
print("="*_sage_const_64 )
print("  CONVERGENCIA DE MOMENTOS CON MUESTRA CRECIENTE")
print("="*_sage_const_64 )
print(f"  Referencia Régimen I (800 pts, resto): freq≈0.223  M4≈2.60")
print(f"  Valor N=21 con 800 pts:               freq=0.110  M4=2.02")
print()
hdr = f"{'k_max':>8} {'n_arco':>8} {'freq':>8} {'M3':>8} {'M4':>8} {'M6':>9} {'ΔM4':>8}"
print(hdr)
print("-"*_sage_const_64 )

resultados_conv = []

for K in MUESTRAS:
    # Tomar los primeros K puntos de la órbita pre-calculada
    xs_k = xs_orbit[:K]

    # Separar positivos y negativos
    pos_mask  = (~np.isnan(xs_k)) & (xs_k > _sage_const_0 )
    arco_mask = pos_mask & (xs_k > N) & (xs_k < _sage_const_2 *N)

    n_pos  = int(np.sum(pos_mask))
    n_arco = int(np.sum(arco_mask))
    n_neg  = K - n_pos - int(np.sum(np.isnan(xs_k)))

    freq = float(n_arco) / float(K)

    arco_vals = xs_k[arco_mask] / float(N)   # R = x/N ∈ (1,2)

    if n_arco < _sage_const_6 :
        print(f"{K:>8}  {n_arco:>8}  {freq:>8.4f}  {'—':>8} {'—':>8} {'—':>9} {'—':>8}")
        continue

    mu    = np.mean(arco_vals)
    sigma = np.std(arco_vals, ddof=_sage_const_1 )
    M3    = float(np.mean((arco_vals - mu)**_sage_const_3 ) / sigma**_sage_const_3 )
    M4    = float(np.mean((arco_vals - mu)**_sage_const_4 ) / sigma**_sage_const_4 )
    M6    = float(np.mean((arco_vals - mu)**_sage_const_6 ) / sigma**_sage_const_6 )
    dM4   = M4 - _sage_const_3p0 

    resultados_conv.append({
        'K': K, 'n_arco': n_arco, 'freq': freq,
        'M3': M3, 'M4': M4, 'M6': M6, 'n_pos': n_pos, 'n_neg': n_neg
    })

    print(f"{K:>8}  {n_arco:>8}  {freq:>8.4f}  {M3:>8.4f}  {M4:>8.4f}  {M6:>9.4f}  {dM4:>+8.4f}")

# ── Diagnóstico de la órbita ─────────────────────────────────
print()
print("="*_sage_const_64 )
print("  DIAGNÓSTICO DETALLADO DE LA ÓRBITA (primeros 20 pasos)")
print("="*_sage_const_64 )
print(f"  {'k':>4}  {'x(kP)':>14}  {'x/N':>8}  {'en arco?':>10}  {'componente'}")
print(f"  {'-'*_sage_const_4 }  {'-'*_sage_const_14 }  {'-'*_sage_const_8 }  {'-'*_sage_const_10 }  {'-'*_sage_const_12 }")
for i in range(min(_sage_const_20 , MAX_K)):
    xv = xs_orbit[i]
    if np.isnan(xv):
        comp = 'O (infinito)'
        en   = '—'
        ratio = '—'
    elif xv > _sage_const_0 :
        comp = 'C∞ (positiva)'
        en_bool = N < xv < _sage_const_2 *N
        en   = '✓ SÍ' if en_bool else '✗ no'
        ratio = f"{xv/N:.5f}"
    else:
        comp = 'C₀ (oval)'
        en   = '✗ no'
        ratio = f"{xv/N:.5f}"
    print(f"  {i+_sage_const_1 :>4}  {xv:>14.4f}  {ratio:>8}  {en:>10}  {comp}")

# ── Distribución de la órbita completa ──────────────────────
print()
print("="*_sage_const_64 )
print(f"  DISTRIBUCIÓN DE LA ÓRBITA COMPLETA (k=1..{MAX_K})")
print("="*_sage_const_64 )
xs_full     = xs_orbit
n_nan       = int(np.sum(np.isnan(xs_full)))
n_pos_full  = int(np.sum((~np.isnan(xs_full)) & (xs_full > _sage_const_0 )))
n_neg_full  = int(np.sum((~np.isnan(xs_full)) & (xs_full <= _sage_const_0 )))
n_arco_full = int(np.sum((~np.isnan(xs_full)) & (xs_full > N) & (xs_full < _sage_const_2 *N)))

print(f"  Total pasos:            {MAX_K}")
print(f"  En oval C₀ (x<0):       {n_neg_full}  ({_sage_const_100 *n_neg_full/MAX_K:.1f}%)")
print(f"  En C∞ positiva (x>0):   {n_pos_full}  ({_sage_const_100 *n_pos_full/MAX_K:.1f}%)")
print(f"  De esos, en arco (N,2N):{n_arco_full}  ({_sage_const_100 *n_arco_full/MAX_K:.1f}% del total)")
if n_pos_full > _sage_const_0 :
    print(f"  Fracción positivos→arco: {n_arco_full/n_pos_full:.4f}  (Régimen I típico ≈ 0.44)")

# Distribución de x/N sobre el arco con histograma de texto
arco_all = xs_full[(~np.isnan(xs_full)) & (xs_full > N) & (xs_full < _sage_const_2 *N)] / float(N)
if len(arco_all) > _sage_const_0 :
    print()
    print("  Histograma de R=x/N en (1,2) — 10 bins:")
    bins_e = np.linspace(_sage_const_1p0 , _sage_const_2p0 , _sage_const_11 )
    counts, _ = np.histogram(arco_all, bins=bins_e)
    max_c = max(counts)
    for j in range(_sage_const_10 ):
        bar = '█' * int(_sage_const_20  * counts[j] / max(max_c, _sage_const_1 ))
        print(f"  [{bins_e[j]:.2f},{bins_e[j+_sage_const_1 ]:.2f})  {bar:<20}  {counts[j]}")

# ── Veredicto ────────────────────────────────────────────────
print()
print("="*_sage_const_64 )
print("  VEREDICTO")
print("="*_sage_const_64 )
if len(resultados_conv) >= _sage_const_2 :
    freq_ini = resultados_conv[_sage_const_0 ]['freq']
    freq_fin = resultados_conv[-_sage_const_1 ]['freq']
    M4_ini   = resultados_conv[_sage_const_0 ]['M4']
    M4_fin   = resultados_conv[-_sage_const_1 ]['M4']
    delta_freq = abs(freq_fin - freq_ini)
    delta_M4   = abs(M4_fin - M4_ini)

    print(f"  freq: {freq_ini:.4f} → {freq_fin:.4f}  (Δ={delta_freq:.4f})")
    print(f"  M4:   {M4_ini:.4f}  → {M4_fin:.4f}   (Δ={delta_M4:.4f})")
    print()
    if freq_fin > _sage_const_0p19  and delta_freq > _sage_const_0p05 :
        print("  → CONVERGENCIA AL RÉGIMEN I: freq se acerca a ≈0.22")
        print("    N=21 es un caso de baja densidad inicial, no un outlier estructural.")
    elif delta_freq < _sage_const_0p02 :
        print("  → OUTLIER ESTRUCTURAL CONFIRMADO: freq se estabiliza fuera de ≈0.22")
        print("    N=21 tiene un comportamiento orbital genuinamente distinto al Régimen I.")
    else:
        print("  → RESULTADO AMBIGUO: se necesitan más puntos para decidir.")
        print("    Considerar extender a k=50000.")
print("="*_sage_const_64 )

